# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.1
_src_path: git+https://gitlab.tuwien.ac.at/cookbooks/templates/tu-cookbook-python
author_email: nikolas.pikall@tuwien.ac.at
author_fullname: Nikolas Pikall
legal_entity: TU Wien
license: MIT
project_description: Notebooks for the Course "Data Retrieval in Earth Observation"
project_name: data-retrieval-in-eo
repo_name: data-retrieval-in-eo
use_license: true
